pm disable-user --user 0 com.samsung.android.game.gametools
pm disable-user --user 0 com.samsung.sdm
# pm disable-user --user 0 com.sec.android.soagent  # disables updates
pm disable-user --user 0 com.wssyncmldm
pm uninstall -k --user 0 android.autoinstalls.config.samsung
pm uninstall -k --user 0 com.android.dreams.phototable
pm uninstall -k --user 0 com.android.egg
pm uninstall -k --user 0 com.android.email
pm uninstall -k --user 0 com.android.exchange
pm uninstall -k --user 0 com.cnn.mobile.android.phone.edgepanel
pm uninstall -k --user 0 com.dsi.ant.plugins.antplus
pm uninstall -k --user 0 com.dsi.ant.sample.acquirechannels
pm uninstall -k --user 0 com.dsi.ant.server
pm uninstall -k --user 0 com.dsi.ant.service.socket
pm uninstall -k --user 0 com.enhance.gameservice
pm uninstall -k --user 0 com.facebook.appmanager
pm uninstall -k --user 0 com.facebook.services
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.google.android.printservice.recommendation
pm uninstall -k --user 0 com.google.vr.vrcore
pm uninstall -k --user 0 com.hancom.office.editor.hidden
pm uninstall -k --user 0 com.hancom.office.editor.hiddenFailure
pm uninstall -k --user 0 com.microsoft.appmanager
pm uninstall -k --user 0 com.microsoft.office.excel
pm uninstall -k --user 0 com.microsoft.office.officehubrow
pm uninstall -k --user 0 com.microsoft.office.powerpoint
pm uninstall -k --user 0 com.microsoft.office.word
pm uninstall -k --user 0 com.microsoft.skydrive
pm uninstall -k --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
pm uninstall -k --user 0 com.samsung.android.app.clipboardedge
pm uninstall -k --user 0 com.samsung.android.app.episodes
pm uninstall -k --user 0 com.samsung.android.app.galaxyfinder
pm uninstall -k --user 0 com.samsung.android.app.ledbackcover
pm uninstall -k --user 0 com.samsung.android.app.ledcoverdream
pm uninstall -k --user 0 com.samsung.android.app.memo
pm uninstall -k --user 0 com.samsung.android.app.news
pm uninstall -k --user 0 com.samsung.android.app.reminder
pm uninstall -k --user 0 com.samsung.android.app.routines
pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
pm uninstall -k --user 0 com.samsung.android.app.sharelive
pm uninstall -k --user 0 com.samsung.android.app.social
pm uninstall -k --user 0 com.samsung.android.app.spage
pm uninstall -k --user 0 com.samsung.android.app.storyalbumwidget
pm uninstall -k --user 0 com.samsung.android.app.taskedge
pm uninstall -k --user 0 com.samsung.android.app.vrsetupwizardstub
pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall -k --user 0 com.samsung.android.ardrawing
pm uninstall -k --user 0 com.samsung.android.aremoji
pm uninstall -k --user 0 com.samsung.android.aremojieditor
pm uninstall -k --user 0 com.samsung.android.arzone
pm uninstall -k --user 0 com.samsung.android.authfw
pm uninstall -k --user 0 com.samsung.android.aware.service
pm uninstall -k --user 0 com.samsung.android.bbc.bbcagent
pm uninstall -k --user 0 com.samsung.android.bixby.agent
pm uninstall -k --user 0 com.samsung.android.bixby.agent.dummy
pm uninstall -k --user 0 com.samsung.android.bixby.service
pm uninstall -k --user 0 com.samsung.android.bixby.wakeup
pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
pm uninstall -k --user 0 com.samsung.android.coldwalletservice
pm uninstall -k --user 0 com.samsung.android.drivelink.stub
pm uninstall -k --user 0 com.samsung.android.email.provider
pm uninstall -k --user 0 com.samsung.android.fmm
pm uninstall -k --user 0 com.samsung.android.forest
pm uninstall -k --user 0 com.samsung.android.galaxycontinuity
pm uninstall -k --user 0 com.samsung.android.game.gamehome
pm uninstall -k --user 0 com.samsung.android.game.gametools
pm uninstall -k --user 0 com.samsung.android.game.gos
pm uninstall -k --user 0 com.samsung.android.game.gosSuccess
pm uninstall -k --user 0 com.samsung.android.gametuner.thin
pm uninstall -k --user 0 com.samsung.android.hmt.vrshell
pm uninstall -k --user 0 com.samsung.android.hmt.vrsvc
pm uninstall -k --user 0 com.samsung.android.homemode
pm uninstall -k --user 0 com.samsung.android.keyguardwallpaperupdator
pm uninstall -k --user 0 com.samsung.android.kidsinstaller
pm uninstall -k --user 0 com.samsung.android.knox.analytics.uploader
pm uninstall -k --user 0 com.samsung.android.knox.attestation
pm uninstall -k --user 0 com.samsung.android.knox.containeragent
pm uninstall -k --user 0 com.samsung.android.knox.containerdesktop
pm uninstall -k --user 0 com.samsung.android.knox.pushmanager
pm uninstall -k --user 0 com.samsung.android.livestickers
pm uninstall -k --user 0 com.samsung.android.lool
pm uninstall -k --user 0 com.samsung.android.mateagent
pm uninstall -k --user 0 com.samsung.android.mdm
pm uninstall -k --user 0 com.samsung.android.mdx
pm uninstall -k --user 0 com.samsung.android.mdx.kit
pm uninstall -k --user 0 com.samsung.android.mdx.quickboard
pm uninstall -k --user 0 com.samsung.android.messaging
pm uninstall -k --user 0 com.samsung.android.mobileservice
pm uninstall -k --user 0 com.samsung.android.net.wifi.wifiguider
pm uninstall -k --user 0 com.samsung.android.networkdiagnostic
pm uninstall -k --user 0 com.samsung.android.oneconnect
pm uninstall -k --user 0 com.samsung.android.privateshare
pm uninstall -k --user 0 com.samsung.android.samsungpass
pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
pm uninstall -k --user 0 com.samsung.android.scloud
pm uninstall -k --user 0 com.samsung.android.service.peoplestripe
pm uninstall -k --user 0 com.samsung.android.service.stplatform
pm uninstall -k --user 0 com.samsung.android.service.travel
pm uninstall -k --user 0 com.samsung.android.smartsuggestions
pm uninstall -k --user 0 com.samsung.android.smartswitchassistant
pm uninstall -k --user 0 com.samsung.android.spay
pm uninstall -k --user 0 com.samsung.android.spayfw
pm uninstall -k --user 0 com.samsung.android.spdfnote
pm uninstall -k --user 0 com.samsung.android.svoice
pm uninstall -k --user 0 com.samsung.android.svoiceime
pm uninstall -k --user 0 com.samsung.android.themestore
pm uninstall -k --user 0 com.samsung.android.tripwidget
pm uninstall -k --user 0 com.samsung.android.visionintelligence
pm uninstall -k --user 0 com.samsung.android.voc
pm uninstall -k --user 0 com.samsung.android.voicewakeup
pm uninstall -k --user 0 com.samsung.android.weather
pm uninstall -k --user 0 com.samsung.android.widgetapp.yahooedge.finance
pm uninstall -k --user 0 com.samsung.android.widgetapp.yahooedge.sport
pm uninstall -k --user 0 com.samsung.desktopsystemui
pm uninstall -k --user 0 com.samsung.groupcast
pm uninstall -k --user 0 com.samsung.safetyinformation
pm uninstall -k --user 0 com.samsung.storyservice
pm uninstall -k --user 0 com.samsung.svoice.sync
pm uninstall -k --user 0 com.samsung.systemui.bixby2
pm uninstall -k --user 0 com.samsung.unifiedtp
pm uninstall -k --user 0 com.samsung.voiceserviceplatform
pm uninstall -k --user 0 com.sec.android.app.billing
pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
pm uninstall -k --user 0 com.sec.android.app.DataCreate
pm uninstall -k --user 0 com.sec.android.app.desktoplauncher
pm uninstall -k --user 0 com.sec.android.app.gamehub
pm uninstall -k --user 0 com.sec.android.app.magnifier
pm uninstall -k --user 0 com.sec.android.app.myfiles
pm uninstall -k --user 0 com.sec.android.app.ocr
pm uninstall -k --user 0 com.sec.android.app.quicktool
pm uninstall -k --user 0 com.sec.android.app.samsungapps
pm uninstall -k --user 0 com.sec.android.app.sbrowser
pm uninstall -k --user 0 com.sec.android.app.SecSetupWizard
pm uninstall -k --user 0 com.sec.android.app.translator
pm uninstall -k --user 0 com.sec.android.app.withtv
pm uninstall -k --user 0 com.sec.android.cover.ledcover
pm uninstall -k --user 0 com.sec.android.daemonapp
pm uninstall -k --user 0 com.sec.android.desktopmode.uiservice
pm uninstall -k --user 0 com.sec.android.easyMover.Agent
pm uninstall -k --user 0 com.sec.android.easyonehand
pm uninstall -k --user 0 com.sec.android.gallery3d
pm uninstall -k --user 0 com.sec.android.mimage.avatarstickers
pm uninstall -k --user 0 com.sec.android.provider.snote
pm uninstall -k --user 0 com.sec.android.sidesync30
pm uninstall -k --user 0 com.sec.android.smartfpsadjuster
pm uninstall -k --user 0 com.sec.android.usermanual
pm uninstall -k --user 0 com.sec.android.widgetapp.diotek.smemo
pm uninstall -k --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall -k --user 0 com.sec.android.widgetapp.samsungapps
pm uninstall -k --user 0 com.sec.android.widgetapp.webmanual
pm uninstall -k --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall -k --user 0 com.sec.epdgtestapp
pm uninstall -k --user 0 com.sec.everglades
pm uninstall -k --user 0 com.sec.everglades.update
pm uninstall -k --user 0 com.sec.factory
pm uninstall -k --user 0 com.sec.kidsplat.installer
pm uninstall -k --user 0 com.sec.location.nsflp2
pm uninstall -k --user 0 com.sec.mhs.smarttethering
pm uninstall -k --user 0 com.sec.readershub
pm uninstall -k --user 0 com.sec.spp.push
pm uninstall -k --user 0 com.sec.vsim.ericssonnsds.webapp
pm uninstall -k --user 0 com.sec.yosemite.phone
pm uninstall -k --user 0 com.skype.raider
pm uninstall -k --user 0 com.tripadvisor.tripadvisor
pm uninstall -k --user 0 com.vlingo.midas
pm uninstall -k --user 0 com.wsomacp
pm uninstall -k --user 0 flipboard.boxer.app
pm uninstall -k --user 0 tv.peel.samsung.app
settings put global animator_duration_scale 0
settings put global transition_animation_scale 0
settings put global window_animation_scale 0
pm uninstall -k --user 0 com.samsung.vvm
pm uninstall -k --user 0 com.samsung.android.calendar

